---
#------------------------------------------------------------------------------
# DevSecOps Workstation Setup Playbook
#------------------------------------------------------------------------------
# This playbook provisions a development workstation using the
# csabapatyi.devsecops_workstation role from Ansible Galaxy.
#
# Usage:
#   ansible-playbook -i inventory.yml setup.yml -e "@os_vars/<your-os>.yml"
#
# Example:
#   ansible-playbook -i inventory.yml setup.yml -e "@os_vars/ubuntu_24.04_extra-vars.yml"
#------------------------------------------------------------------------------

- name: Provision DevSecOps Workstation
  hosts: localhost
  gather_facts: true
  become: false

  pre_tasks:
    - name: Display target system information
      ansible.builtin.debug:
        msg: |
          Target System: {{ ansible_distribution }} {{ ansible_distribution_version }}
          Architecture: {{ ansible_architecture }}
          User: {{ ansible_user_id }}

  roles:
    - role: csabapatyi.devsecops_workstation

  post_tasks:
    - name: Display completion message
      ansible.builtin.debug:
        msg: |
          ════════════════════════════════════════════════════════════════
          Workstation provisioning complete!

          Please log out and back in for all changes to take effect.
          ════════════════════════════════════════════════════════════════
